version: "3.9"

services:
  jrpc-server:
    image: jrpc-server
    container_name: jrpc-server-container
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        VERSION: 0.0.1
        NAME: node-jrpc-server
    ports:
      - "3000:3000"
    links:
      - db
    command: yarn start
  db:
    image: postgres:14.5-alpine
    container_name: postgres-container
    environment:
      TZ: 'GMT+5'
      PGTZ: 'Asia/Tashkent'
      POSTGRES_USER: test_db
      POSTGRES_PASSWORD: test_db
      POSTGRES_DB: test_db
      PGDATA: /data
    volumes:
      - ./pg/data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_db"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"