version: "3.9"

services:
  jrpc-server:
    image: server
    container_name: server-container
    environment:
      - LOG_PATH=./log.txt
      - CONF_PATH=../../../../config.yaml
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        VERSION: 0.0.1
        NAME: node-server
    ports:
      - "127.0.0.3:3000:3000"
    depends_on:
      - db
    command: yarn start
  redis:
    image: redis:7.0.5
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes: 
      - ./redis:/data
    environment:
      - REDIS_HOST=redis
      - REDIS_USER=redis_user
      - REDIS_PASSWORD=redis_password
  db:
    image: postgres:14.5-alpine
    container_name: postgres-container
    environment:
      TZ: 'GMT+5'
      PGTZ: 'Asia/Tashkent'
      POSTGRES_USER: test_db
      POSTGRES_PASSWORD: test_db
      POSTGRES_DB: test_db
      PGDATA: /data
    volumes:
    - ./pg:/docker-entrypoint-initdb.d
    - ./pg/data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_db"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"