version: "3.9"

services:
  jrpc-server:
    image: server
    container_name: server-container
    environment:
      - LOG_PATH=./log.txt
      - CONF_PATH=../../../../config.yaml
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        VERSION: 0.0.1
        NAME: node-server
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: yarn start 
  db:
    image: postgres:14.5-alpine
    container_name: postgres-container
    environment:
      TZ: 'GMT+5'
      PGTZ: 'Asia/Tashkent'
      POSTGRES_USER: test_db
      POSTGRES_PASSWORD: test_db
      POSTGRES_DB: test_db
      PGDATA: /data
    volumes:
    - ./pg:/docker-entrypoint-initdb.d
    - ./pg/data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_db"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"